### ISSUE TITLE
Energy consumption of CPU is 0

### ISSUE THREAD

**Issue by ruomengh** [sustainable-computing-io/kepler#295] opened 2022-10-12 08:56 UTC
**Describe the bug**
Checking "Pod Current Energy Consumption" on Grafana dashboard, CPU energy consumption of each pod is 0. Checking Prometheus, "pod_curr_energy_in_core_millijoule" of all pods are 0. "Total" and "DRAM" have data but "CPU" is 0. 

 The issue exists on both RHEL8.6 and Ubuntu 22.04 host.

**Comment by Feelas** [comment] 2022-10-12 09:54
@rootfs I have also seen this happening in recent commits, can this be related to #120, #150 and #156? I have lost track of changes made in the core energy department, but there has been some movement in this matter, no?

@ruomengh what CPU are you using? Maybe there is different handling of RAPL on various CPUs if some are not seeing this.

**Comment by ruomengh** [comment] 2022-10-13 03:13
There are several nodes using different Intel CPUs in my cluster. All of them have the same issue after running for a while. When a new node just joined the cluster, it can show CPU energy.

**Comment by Feelas** [comment] 2022-10-13 07:38
I have seen one similar bug from a few months before, #96. @rootfs, how can we check if this is an instance of that?

**Comment by marceloamaral** [comment] 2022-10-13 08:08
Are you running Kepler in a Bare-metal node?

There some architecture that does not report the CPU core power...
For example the node that I have, I can only see the package power (i.e., CPU socket)

Can you run the following application in your node?
https://github.com/deater/uarch-configure/tree/master/rapl-read

**Comment by rootfs** [comment] 2022-10-13 17:21
@ruomengh if `pod_curr_energy_in_core_millijoule` has values and becomes 0 after a while, that could have a few possible reasons:
- do you happen to see any value in `pod_curr_energy_in_pkg_millijoule` metrics?
- the pod is not actively using cpu, so eBPF program cannot detect it. The metrics then turns to 0. To see if this is the case, can you find and kill the process (not delete the pod) in the container that has this problem?
- there are some potential stat reading problem. Can you see if `node_energy_stat` metrics is there and `node_curr_energy_in_pkg_joule` in that metrics is non-zero?
- can you turn on verbosity and redeploy kepler so we can see the logs? e.g. set `v=5` [here](https://github.com/sustainable-computing-io/kepler/blob/main/manifests/kubernetes/deployment.yaml#L84)

**Comment by Feelas** [comment] 2022-10-14 07:27
> Can you check the pkg energy `pod_curr_energy_in_pkg_millijoule ` and check if there are any readings there?

Both through metrics and directly in Kepler verbose log, I can see that the package and DRAM energies are reported as nonzero, while eCore stays 0. Sample log parts:
```
I1014 07:23:47.547824       1 node_energy.go:95] node energy stat core 0 (0) dram 58632 (47861778) uncore 0 (0) pkg 559072 (354463555)
gpu 0 sensor 0 (0)
```
```
I1014 07:23:47.547993       1 reader.go:362] energy from pod (1 processes): name: console-dd56f49d4-qzm78 namespace: openshift-console
        cgrouppid: 0 pid: 13172 comm: bridge
        ePkg (mJ): 9809 (4859081) (eCore: 0 (0) eDram: 1029 (516579) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
```

Both node_curr_energy_in_pkg_joule and node_energy_stat seem to work properly.

**Comment by ruomengh** [comment] 2022-10-17 01:51
> thank you @Feelas so this is indeed a result of #150 and #156. We trust the pkg energy than the old way of deriving missing core energy (when core RAPL domain is missing)
> 
> @ruomengh can you check the `pod_curr_energy_in_pkg_millijoule` and `node_curr_energy_in_pkg_joule` on your setup?

node_curr_energy_in_pkg_joule{container="kepler-exporter",` endpoint="http", exported_instance="css-dev-ken", instance="css-dev-ken", job="kepler-exporter", namespace="kepler", pod="kepler-exporter-8swnk", service="kepler-exporter"}

pod_curr_energy_in_pkg_millijoule{command="adapter", container="kepler-exporter", endpoint="http", instance="css-dev-ken", job="kepler-exporter", namespace="kepler", pod="kepler-exporter-8swnk", pod_name="prometheus-adapter-678b454b8b-vt7mp", pod_namespace="monitoring", service="kepler-exporter"}

**Comment by ruomengh** [comment] 2022-10-17 02:40
> > Can you check the pkg energy `pod_curr_energy_in_pkg_millijoule ` and check if there are any readings there?
> 
> Both through metrics and directly in Kepler verbose log, I can see that the package and DRAM energies are reported as nonzero, while eCore stays 0. Sample log parts:
> 
> ```
> I1014 07:23:47.547824       1 node_energy.go:95] node energy stat core 0 (0) dram 58632 (47861778) uncore 0 (0) pkg 559072 (354463555)
> gpu 0 sensor 0 (0)
> ```
> 
> ```
> I1014 07:23:47.547993       1 reader.go:362] energy from pod (1 processes): name: console-dd56f49d4-qzm78 namespace: openshift-console
>         cgrouppid: 0 pid: 13172 comm: bridge
>         ePkg (mJ): 9809 (4859081) (eCore: 0 (0) eDram: 1029 (516579) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
> ```
> 
> Both node_curr_energy_in_pkg_joule and node_energy_stat seem to work properly.



> @ruomengh @Feelas if `pod_curr_energy_in_core_millijoule` has values and becomes 0 after a while, that could have a few possible reasons:
> 
> * do you happen to see any value in `pod_curr_energy_in_pkg_millijoule` metrics?
> * the pod is not actively using cpu, so eBPF program cannot detect it. The metrics then turns to 0. To see if this is the case, can you find and kill the process (not delete the pod) in the container that has this problem?
> * there are some potential stat reading problem. Can you see if `node_energy_stat` metrics is there and `node_curr_energy_in_pkg_joule` in that metrics is non-zero?
> * can you turn on verbosity and redeploy kepler so we can see the logs? e.g. set `v=5` [here](https://github.com/sustainable-computing-io/kepler/blob/main/manifests/kubernetes/deployment.yaml#L84)

@rootfs  
1. `pod_curr_energy_in_pkg_millijoule` has values for all pods
2. `node_curr_energy_in_pkg_joule` is not 0, but `node_energy_stat` is 0

**Comment by marceloamaral** [comment] 2022-10-17 04:07
> pod_curr_energy_in_pkg_millijoule has values for all pods

This is good, it means that the pod energy consumption is being calculated

> node_curr_energy_in_pkg_joule is not 0

This metric `node_curr_energy_in_pkg_joule` is used to calculate the `pod_curr_energy_in_pkg_millijoule`

----
RAPL can expose the power consumption of CORE, UNCORE, PKG, DRAM or PLATFORM
However, not all systems expose all these metrics.
And most likely your system only has CORE and DRAM!
So that's why you can't see `pod_curr_energy_in_core_millijoule`, but you can see `pod_curr_energy_in_pkg_millijoule`...

Note that package means socket in intel RAPL terminology...


----
There are some works that use pkg instead of core, when the later is not available.... But pkg is not the core, it has many more components involved. We decided to make it transparent to the user...

I understand it should be better documented, but this is not a bug, it's how the system should be working...

**Comment by ruomengh** [comment] 2022-10-17 05:41
Yes, RAPL package measures the energy consumption of the entire socket. It includes the consumption of all the cores, integrated graphics and also the uncore components. If CPU is the only thing of concern for Kepler for now, it makes sense to display core other than pkg. No matter cpu or pkg is exposed to users, cpu = 0 looks like a bug to me.  
Besides, the issue doesn't exist on all nodes. I have a node which just joined the cluster, pod CPU consumption on this node are not 0.

**Comment by marceloamaral** [comment] 2022-10-17 07:41
> RAPL package measures the energy consumption of the entire socket. It includes the consumption of all the cores, integrated graphics and also the uncore components

Right, we cannot use this as the CORE energy...

>No matter cpu or pkg is exposed to users, cpu = 0 looks like a bug to me.

We could disable the core energy if it is not possible to export....but missing metrics will also looks like a bug....
Anyway, I think that as far as it will be well documented, this should not be a big concern....

**Comment by rootfs** [comment] 2022-10-17 13:45
@marceloamaral good analysis!

@ruomengh would you like to post a documentation PR on this issue? Thanks!

**Comment by rootfs** [comment] 2022-12-15 13:21
there is a trouble shooting guide in doc that covers this case, we can close this issue now.

**Closed by rootfs** 2022-12-15 13:21 UTC
